config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, except: :index do
    resource :subscription, only: [:create, :destroy]
  end
  devise_for :accounts, controllers: {registrations: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest
end

app/models/user.rb
class User < ApplicationRecord
  # Subscriber associations
  has_many :subscriptions, foreign_key: :user_id, dependent: :destroy
  has_many :followers, through: :subscriptions, source: :follower

  # Subscriptions associations
  has_many :reverse_subscriptions, class_name: "Subscription", foreign_key: :follower_id, dependent: :destroy
  has_many :following, through: :reverse_subscriptions, source: :user

  belongs_to :account
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nickname, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :user_already_exist, only: %i[new create]
  before_action :user_page_owner, only: %i[edit update destroy]

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.account.destroy!
    redirect_to new_account_session_path, notice: "User was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def user_already_exist
    unless current_account.user.nil?
      redirect_to root_path, alert: "Your profile already exists for your account."
    end
  end

  def user_page_owner
    unless @user == current_account.user
      redirect_to @user, alert: "You are not the owner of this account."
    end
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :bio).merge(account_id: current_account.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p style="margin-top: 60px;">
    <%= user.nickname %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= "#{user.last_name} #{user.first_name}" %>
  </p>

  <p>
    <strong>Bio:</strong>
    <p>
      <%= user.bio %>
    </p>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= button_to "Show this user", @user, method: :get %>
</div>

app/views/users/new.html.erb
<% content_for :title, "Tell about yourself" %>

<h1>New user</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= render @user %>

<% unless @user == current_account.user %>
  <% if current_account.user.following.include?(@user) %>
    <%= button_to 'Отписаться', user_subscription_path(@user), method: :delete, class: 'btn btn-warning' %>
  <% else %>
    <%= button_to 'Подписаться', user_subscription_path(@user), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= button_to "Back to posts", posts_path, method: :get %>
<% if @user == current_account.user %>    
  <div style="display: flex; gap: 10px;">
    <%= button_to "Edit this user", edit_user_path(@user), method: :get %>
    

    <%= button_to "Destroy this user", @user, method: :delete %>
  </div>
<% end %>


<% if @user.posts %>
  <div id="posts">
    <% @user.posts.order(created_at: :desc).each do |post| %>
      <%= render post %>
      <p>
        <%= button_to "Show this post", post, method: :get %>
      </p>
    <% end %>
  </div>
<% end %>