config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, except: :index do
    resource :subscription, only: [:create, :destroy]
  end
  devise_for :accounts, controllers: {registrations: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest
end

app/models/post.rb
class Post < ApplicationRecord
  include PhotoUploader::Attachment(:photo) # adds an `photo` virtual attribute

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :text, presence: true

  def total_likes
    likes.sum(:value)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :user_exist
  before_action :post_owner, only: %i[edit update destroy]

  # GET /posts
  def index
    following_posts = Post.joins(user: :followers)
      .where(subscriptions: {follower_id: current_account.user.id})

    own_posts = Post.where(user_id: current_account.user.id)

    @posts = Post.where(id: following_posts.pluck(:id) + own_posts.pluck(:id))
      .order(created_at: :desc)
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!
    redirect_to posts_url, notice: "Post was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def user_exist
    unless current_account.user
      redirect_to new_user_path, alert: "To continue working on the site, you need to create your own page."
    end
  end

  def post_owner
    unless @post.user == current_account.user
      redirect_to @post, alert: "You are not the owner of this post."
    end
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:text, :photo).merge(user_id: current_account.user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <%= link_to post.user.nickname, post.user %>
  </p>

  <p>    
    <%= post.text %>
  </p>

  <% if post.photo %>
    <p>
      <%= image_tag post.photo_url(:thumb) %>
    </p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div style="display: flex; gap: 10px; margin-top: 60px;"> 
  Welcome, <%= link_to current_account.user.nickname, current_account.user %>
  <%= button_to 'Sign Out', destroy_account_session_path, method: :delete %>
</div>

<% content_for :title, "Posts" %>

<h1>Posts</h1>
<%= button_to "New post", new_post_path, method: :get %>

<% if @posts %>
  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <p>
        <%= button_to "Show this post", post, method: :get %>
      </p>
    <% end %>
  </div>
<% end %>

<% unless User.where.not(id: current_account.user.id).empty? %>
  <h3> Other users </h3>
  <% User.where.not(id: current_account.user.id).each do |user| %>
    <p>
      <%= link_to user.nickname, user %>
    </p>
  <% end %>
<% end%>

  

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<%= button_to "Back to posts", posts_path, method: :get %>
<% if @post.user == current_account.user %>
  <div style="display: flex; gap: 10px;">
    <%= button_to "Edit this post", edit_post_path(@post), method: :get %>
    

    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
<% end %>


<p><strong>Likes: <%= @post.total_likes %></strong></p>

<div style="display: flex; gap: 10px;">
  <% if @post.likes.find_by(user: current_account.user)&.value == 1 %>
    <%= button_to 'Like', post_like_path(@post), method: :delete %>
    <%= button_to 'Dislike', post_likes_path(@post), method: :post, params: { like: { value: -1 } } %>
  <% elsif @post.likes.find_by(user: current_account.user)&.value == -1 %>
    <%= button_to 'Like', post_likes_path(@post), method: :post, params: { like: { value: 1 } } %>
    <%= button_to 'Dislike', post_like_path(@post), method: :delete %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post, params: { like: { value: 1 } } %>
    <%= button_to 'Dislike', post_likes_path(@post), method: :post, params: { like: { value: -1 } } %>
  <% end %>
</div>

<h3>Comments</h3>
<%= form_with(model: [ @post, Comment.new ], local: true) do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <div class="actions">
    <%= form.submit "Add Comment" %>
  </div>
<% end %>

<ul>
  <% @post.comments.each do |comment| %>
    <li>
      <strong><%= comment.user.nickname %>:</strong>
      <%= comment.text %>
      <% if comment.user == current_account.user %>
        <%= button_to 'Delete', [@post, comment], method: :delete%>
      <% end %>
    </li>
  <% end %>
</ul>